from mininet.topo import Topo
class MyTopo(Topo):
    def __init__(self):
        Topo.__init__(self)

        BerlinH=self.addHost('BH')
        HamburgH=self.addHost('HH')
        MonachiumH=self.addHost('MH')
        KoloniaH=self.addHost('KH')
        FrankfurtH=self.addHost('FH')
        StuttgardH=self.addHost('SH')
        DusseldorfH=self.addHost('DH')
        LipskH=self.addHost('LH')
        DortmundH=self.addHost('DortH')
        EssenH=self.addHost('EH')

        BerlinS = self.addHost('BS')
        HamburgS = self.addHost('HS')
        MonachiumS = self.addHost('MS')
        KoloniaS = self.addHost('KS')
        FrankfurtS = self.addHost('FS')
        StuttgardS = self.addHost('SS')
        DusseldorfS = self.addHost('DS')
        LipskS = self.addHost('LS')
        DortmundS = self.addHost('DortS')
        EssenS = self.addHost('ES')

        self.addLink(BerlinH, BerlinS)
        self.addLink(HamburgH, HamburgS)
        self.addLink(MonachiumH, MonachiumS)
        self.addLink(KoloniaH, KoloniaS)
        self.addLink(FrankfurtH, FrankfurtS)
        self.addLink(StuttgardH, StuttgardS)
        self.addLink(DusseldorfH, DusseldorfS)
        self.addLink(LipskH, LipskS)
        self.addLink(DortmundH, DortmundS)
        self.addLink(EssenH, EssenS)

        self.addLink(BerlinS, HamburgS)
        self.addLink(HamburgS, KoloniaS)
        self.addLink(HamburgS, DortmundS)
        self.addLink(HamburgS, MonachiumS)
        self.addLink(BerlinS, KoloniaS)
        self.addLink(BerlinS, LipskS)
        self.addLink(BerlinS, MonachiumS)
        self.addLink(LipskS, FrankfurtS)
        self.addLink(MonachiumS, StuttgardS)
        self.addLink(MonachiumS, KoloniaS)
        self.addLink(StuttgardS, FrankfurtS)
        self.addLink(KoloniaS, DusseldorfS)
        self.addLink(KoloniaS, FrankfurtS)
        self.addLink(KoloniaS, StuttgardS)
        self.addLink(EssenS, DortmundS)
        self.addLink(EssenS, DusseldorfS)
        self.addLink(DortmundS, DusseldorfS)

topos = {'MyTopo': (lambda: MyTopo())}

